name: 'main'

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

permissions:
  id-token: write
  contents: read

jobs:

  stage:
    name: 'stage'
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'safe-to-stage' }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout PR
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Install NPM/yarn
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Yarn Install
        run: cd idnmd && yarn install

      # Test Application
      - name: Yarn Test
        run: cd idnmd && yarn test
        env:
          ENVIRONMENT: "test"

  push:
    name: 'push'
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM/yarn
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Yarn Install
        run: cd idnmd && yarn install

      # Test Application
      - name: Yarn Test
        run: cd idnmd && yarn test
        env:
          ENVIRONMENT: "test"
